# Numpy

Numerical Python - 
Numeric & Scientific Computing

In [1]:
import numpy as np

### Single-Dimension Array

In [2]:
sda=np.array([1,2,3,4,5])
sda

array([1, 2, 3, 4, 5])

### Multi-Dimension Array

In [3]:
mda=np.array([[1,2,3,4,5],[6,7,8,9,10]])
mda

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Array Type

In [4]:
print(type(sda))
print(type(mda))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Initializing Numpy Array with Zeros

In [5]:
n0=np.zeros((2,2))
n0

array([[0., 0.],
       [0., 0.]])

### Initializing Numpy Array with Same Number

In [6]:
n1=np.full((2,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10]])

### Initializing Numpy Array within a range

In [7]:
n2=np.arange(10,20)
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
n2=np.arange(2,11,2)
n2

array([ 2,  4,  6,  8, 10])

### Initializing Numpy Array within random numbers

In [9]:
n3=np.random.randint(10,100,10)
n3

array([79, 68, 36, 61, 78, 91, 98, 74, 74, 14])

### Check and Change shape of Array

In [10]:
n4=np.array([[1,2,3],[4,5,6]])
n4

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
n4.shape

(2, 3)

### Reshape

In [12]:
nrs=np.arange(1,10).reshape(3,3)
nrs

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Dimensions

In [13]:
nd=np.arange(1,10)
nd.ndim

1

In [14]:
nd=np.arange(1,10).reshape(3,3)
nd.ndim

2

In [15]:
nd=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(nd)
print('\nDimensions:',nd.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Dimensions: 3


### Joining Arrays

In [16]:
n1=np.array([1,2,3])
n2=np.array([10,20,30])
n3=np.array([100,200,300])

In [17]:
np.vstack((n1,n2,n3))

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [18]:
np.hstack((n1,n2,n3))

array([  1,   2,   3,  10,  20,  30, 100, 200, 300])

In [19]:
np.column_stack((n1,n2,n3))

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300]])

### Union

In [20]:
n1=np.array([10,20,30,40,50])
n2=np.array([50,60,70,80,90])

In [21]:
np.union1d(n1,n2)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

### Intersection & Difference

In [22]:
np.intersect1d(n1,n2)

array([50])

In [23]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [24]:
np.setdiff1d(n2,n1)

array([60, 70, 80, 90])

### Mathematics Operations on Arrays

In [25]:
n1=np.array([10,30])
n2=np.array([20,40])

In [26]:
np.sum([n1,n2])

100

In [27]:
np.sum([n1,n2],axis=0)

array([30, 70])

In [28]:
np.sum([n1,n2],axis=1)

array([40, 60])

In [29]:
n2=n1+5
n2

array([15, 35])

In [30]:
n2=n1-5
n2

array([ 5, 25])

In [31]:
n2=n1*5
n2

array([ 50, 150])

In [32]:
n2=n1/5
n2

array([2., 6.])

#### Mean

In [33]:
np.mean(n1)

20.0

#### Standard Deviation

In [34]:
np.std(n1)

10.0

#### Median

In [35]:
np.median(n1)

20.0

### Saving and Loading Numpy Array

In [36]:
n1=np.arange(0,101,2)
n1

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [37]:
np.save('even_numbers',n1)

In [38]:
n2=np.load('even_numbers.npy')
n2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### References:

https://olympus.mygreatlearning.com/courses/10899


https://www.w3schools.com/python/numpy/default.asp